---
spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: none

aws:
  region: us-east-2
  sns:
    name:
    topic:
      arn:
  cognito:
    poolId:
    clientAppId:
    fedPoolId:
    userName:
    userPass:

---
spring:
  profiles: local
