---
spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: none

aws:
  accessKey:
  secretKey:
  region: ap-northeast-1
  sns:
    name:
    topic:
      arn:
    platformApplication:
      arn:
  cognito:
    poolId:
    clientAppId:
    fedPoolId:
    userName:
    userPass:

---
spring:
  profiles: local
